
[catalogue]
catalogue.bongu.online

[frontend]
frontend.bongu.online

[mongodb]
mongodb.bongu.online

[cart]
cart.bongu.online

[redis]
redis.bongu.online

[mysql]
mysql.bongu.online

[rabbitmq]
rabbitmq.bongu.online

[user]
user.bongu.online

[payment]
payment.bongu.online

[shipping]
shipping.bongu.online

[all:vars]
ansible_user= ec2-user
ansible_password= DevOps321

[local]
localhost