- name: instaiing redis in remote server
  hosts: redis
  become: yes
  tasks:
    - name: disabling redis
      ansible.builtin.command: dnf module disable redis -y

    - name: enabling redis
      ansible.builtin.command: dnf module enable redis:7 -y

    - name: installing redis
      ansible.builtin.package:
        name: redis
        state: present

    # - name: staring redisdb
    #   ansible.builtin.service:
    #     name: redis
    #     state: started
    #     enabled: yes

    - name: Update API server IP address
      ansible.builtin.replace:
        path: /etc/redis/redis.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'
    
    - name: Update address
      ansible.builtin.lineinfile:
        path: /etc/redis/redis.conf
        regexp: 'protected-mode yes'
        line: 'protected-mode no'
    
    - name: Restart the service nginx
      ansible.builtin.service:
        name: redis
        state: restarted
