- name: installing user services
  hosts: user
  become: yes
  tasks:
    - name: disableing nodejs
      ansible.builtin.command: dnf module disable nodejs -y
    
    - name: enabling nodejs
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: installing nodejs
      ansible.builtin.package:
        name: nodejs
        state: present

    - name: Create a system user for the application
      ansible.builtin.user:
        name: roboshop
        comment: "roboshop system user"
        shell: /sbin/nologin  # Prevents interactive login
        system: yes               # Creates a system account (usually lower UID) # Creates /home/webapp
        state: present

    - name: delete a directory if it does exist
      ansible.builtin.file:
        path: /app 
        state: absent

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /app 
        state: directory

    - name: deleting zip if exist
      ansible.builtin.file:
        path: /tmp/user.zip
        state: absent

    - name: Download zip
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
        dest: /tmp/user.zip
    
    - name: Extract user.zip
      ansible.builtin.unarchive:
        src: /tmp/user.zip
        dest: /app
        remote_src: yes
    
    - name: Install packages based on package.json.
      community.general.npm:
        path: /app
    
    - name: copying user_service
      ansible.builtin.copy:
        src: user.service
        dest: /etc/systemd/system/user.service
  
    # - name: start nad enable mongodb
    #   ansible.builtin.service:
    #     name: catalogue
    #     enabled: yes
    #     state: started

    - name: demon reload
      ansible.builtin.systemd_service:
        name: user
        enabled: yes
        state: restarted
        daemon_reload: true
